name: rockpis-wifivoucher

services:
  db:
    image: mariadb:10.11
    container_name: mariadb_nds
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: radius_db
      MYSQL_USER: radius
      MYSQL_PASSWORD: radius_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          memory: 150M

  api:
    build: .
    container_name: node_api
    restart: always
    network_mode: "host"
    environment:
      - API_KEY=rahasia-appsheet-123
      - ADMIN_PIN=123456
      - DB_HOST=127.0.0.1
      - DB_USER=radius
      - DB_PASSWORD=radius_password
      - DB_NAME=radius_db
    volumes:
      - /tmp:/tmp
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 100M

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: always
    command: tunnel run --token eyJhIjoiYTAwODhkZGI1OGE3ODg0MDIyZmFhMzI5NmM0MDE3MzkiLCJ0IjoiMzlhZDY2MGMtNzg1OC00NGM2LWE4MzEtZDliMzdlYWM1MDgzIiwicyI6IlpXTTRNamcxTldFdFlXTmtOUzAwTkRWaExXRXhPVGd0TldJeVlURXhNelpqTlRoaiJ9
    deploy:
      resources:
        limits:
          memory: 50M

volumes:
  db_data:
    name: rockpis_voucher_db_data

